### ISSUE TITLE
StateColab issue with TodoItemInlineEditor on Android 7.0

### ISSUE THREAD

**Issue by defio** [googlecodelabs/android-compose-codelabs#72] opened 2021-01-02 15:10 UTC
In devices or emulators with Android 7.0 it is impossible to edit properly the text of an item in the todo list.

The problem can be reproduced through the following steps:
1. checkout of the codelab
2. install the "finished" module app on the device or emulator **with Android 7.0 (24)**.
3. click on the button "Add random Item".
4. click on the task that has just been added to the list
5. try editing the text

It is impossible to add to the text, but it is possible to delete characters. 

In other physical devices or emulators with versions different from Android 7.0 (24) everything works as expected.

**Comment by florina-muntenescu** [comment] 2021-01-08 14:33
Using an emulator with API 24 I am unable to reproduce this.

**Comment by defio** [comment] 2021-01-08 15:52
Branch main, commit 52f22aabd7d06b89beaaf874bb71e995f388671f

Android Studio Arctic Fox | 2020.3.1 Canary 3
Build #AI-202.7319.50.2031.7019041, built on December 8, 2020
Runtime version: 11.0.8+10-b944.6842174 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.15.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.developerphil.adbidea

Android Gradle Plugin version: 7.0.0-alpha03
Gradle version: 6.8-rc-1
Compose version: 1.0.0-alpha09
Kotlin version: 1.4.21

Physical device:
- board: universal7420
- brand: samsung
- cpu.abi: arm64-v8a
- cpu.abilist: arm64-v8a,armeabi-v7a,armeabi
- cpu.abilist32: armeabi-v7a,armeabi
- cpu.abilist64: arm64-v8a
- device: zeroflte
- locale: en-GB
- manufacturer: samsung
- model: SM-G920F
- name: zerofltexx
- version.release: 7.0
- version.sdk: 24


https://user-images.githubusercontent.com/6303224/104033143-6e90de00-51cf-11eb-82a3-84713be8ae2e.mp4

unfortunately I can no longer reproduce the same problem with the emulator

**Comment by florina-muntenescu** [comment] 2021-01-10 18:20
Thanks for the details. This doesn't look like an issue with the codelab, but with Compose.
I created an issue for this [here](https://issuetracker.google.com/177166237). 

Closing this issue.

**Closed by florina-muntenescu** 2021-01-10 18:20 UTC

**Comment by florina-muntenescu** [comment] 2021-03-31 13:30
@defio - our engineers have some questions for you to help fix this issue.
Would you mind adding a comment to the [official issue](https://b.corp.google.com/issues/177166237) so they can start asking some questions? 

Thanks!

**Comment by defio** [comment] 2021-04-01 08:32
@florina-muntenescu  of course! I just commented on the ticket in the official issue.
